### ISSUE TITLE
Downloader got stuck in the infinite loop

### ISSUE THREAD

**Issue by manhtranduy** [olivierhagolle/peps_download#40]
Dear Mr. Olivier,
Thank you for developing such a very effective tool to download the Sentinel products.

Recently, I have been trying to download Sentinel-2 images covering the French Guiana area in a period from 2015 until now. 
However, whenever I execute the program, it gets stuck and does not download the remaining images.
It keeps saying: "5 remaining products are on tape, lets's wait 1 minute before trying again"
Could you please help me solve this problem?

Here is my command line:
python ./peps_download.py -c S2ST -t 21NZG -a peps.txt -d 2019-01-01 -f 2020-08-21 -p S2MSI1C

All the best,
Manh
![error](https://user-images.githubusercontent.com/69975017/90905914-26fce780-e3d1-11ea-8b0f-78abd3e86fc1.PNG)

**Comment by olivierhagolle** [comment]
Hi Manh,
what I have heard is that there is a tool internally that sends requests to PEPS every second or so, and uses all its ressources for downloading products. As it is a vacation period, things take longer to be solved. I hope it will work better next week.

If necessary, please send a request to exppeps@cnes.fr, it is the team in charge of maintaining the peps platform. I just developped this tool because I needed it.

And good luck with the clouds in Guyana. Our own L2A products, within THEIA, are not very good there. But we have recently improved the resolution of cloud detection within our procesor, and hope to have better results when it comes to production (end 2020 or begin 2021). 

Best regards
Olivier

**Comment by manhtranduy** [comment]
Thank you for your kind response which immensely helps me to figure out the issue. 

As I understand, so it's the problem due to the PEPS's server. There's nothing we can do but contacting the PEPS team or waiting for the server to analyze the request.
You are absolutely right, the clouds and the sun glint effect are huge obstacles there in French Guiana. And your advice about L2A products from THEIA is also worthy to give it a try. Thanks for the updated information.

Have a good day,
Manh

**Comment by olivierhagolle** [comment]
My colleagues from exppeps@cnes.fr told me that downloading a product on taope is still very long due to a large order of an internal user who has been given a high priority.
If needed you may contact them to ask them to put a list of data on a server where you will be able to download them.
Sorry for this issue!
Best regards
Olivier
